<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGcTdclH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGcTdclH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGcTdclH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGcTdclH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGcTdclH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GcTdclH',
    'container.build_id' => 'e07f0c82',
    'container.build_time' => 1573226766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGcTdclH');
