<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4iRFnjK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4iRFnjK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4iRFnjK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4iRFnjK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container4iRFnjK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '4iRFnjK',
    'container.build_id' => '8e604efa',
    'container.build_time' => 1573230563,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4iRFnjK');
